### ISSUE TITLE
Pass Link to the header of the request to a  Orion-LD Catalogue

### ISSUE THREAD

**Issue by kosgobakis** [OPSILab/Idra#93]
How i can insert the Link (url to the ngsi-context.jsonld file) as a header to the request for Orion-LD Catalogue ?
When i create a new catalogues -> ORION-> NGSI-LD -> Add/Update file, there is no option to add the Link as variable. I can only insert fiwareService and fiwareServicePath.
Without the Link (jsonld file) i cannot access the value of the IOT sensor.
 
**With Link to the header**

curl -G -X GET 'http://localhost:1026/ngsi-ld/v1/entities/' \
    -H 'fiware-service: openiot' \
    -H 'fiware-servicepath: /'  \
    -H 'Link: <http://context-provider:3000/data-models/ngsi-context.jsonld>'\
    -d 'id=urn:ngsi-ld:Device:temperature001' \
    -d 'attrs=temperature'| jq . 

[
  {
    "@context": "http://context-provider:3000/data-models/ngsi-context.jsonld",
    "id": "urn:ngsi-ld:Device:temperature001",
    "type": "TemperatureSensor",
    "temperature": {
      "value": 24,
      "type": "Property",
      "unitCode": "CEL",
      "observedAt": "2021-07-19T11:31:26.331Z"
    }
  }
]

**Without Link to the header**

curl -G -X GET 'http://localhost:1026/ngsi-ld/v1/entities/' \
    -H 'fiware-service: openiot' \
    -H 'fiware-servicepath: /'  \
    -d 'id=urn:ngsi-ld:Device:temperature001' \
    -d 'attrs=temperature'| jq .->

Empty: []

**Comment by robcalla** [comment]
Sorry for the inconvenience, we are working on adding this header.
